name: dddanmar.net
markdown: redcarpet
pygments: true
github: https://www.github.com/dddanmar
about: DevOps Engineer, Team Builder, AWS Lover, All Round Great Guy from the Gold Coast.
urls:
    - text: github
      url: https://github.com/dddanmar
    - text: email
      url: mailto:dddanmar@gmail.com
    - text: guvera
      url: http://guvera.com
    - text: fradio
      url: http://fradio.com
