---
title: dddanmar
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
email: dddanmar@gmail.com
description: DevOps Engineer, Team Builder, AWS Lover, All Round Great Guy from the
  Gold Coast.
baseurl: ''
url: http://dddanmar.net
twitter_username: dddanmar
github_username: dddanmar
facebook_username: dddanmar
comments: true
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
